-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 17:08:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema final-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final-project` DEFAULT CHARACTER SET utf8 ;
USE `final-project` ;

-- -----------------------------------------------------
-- Table `final-project`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Products` (
  `idProduct` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `price` DECIMAL(8,2) NULL,
  `description` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `imagePath` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `final-project`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Customers` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Orders` (
  `idOrder` INT NOT NULL,
  `OrderDate`  DATE NULL,
  `idCustomer` int NULL,
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `idCustomer`
    FOREIGN KEY (idCustomer)
    REFERENCES Customers(idCustomer)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`OrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`OrderItems` (
  `idOrderItem` INT NOT NULL,
  `idProduct`int NULL,
  `checkout_price` double NULL,
  `idOrder` int NULL,
  PRIMARY KEY (`idOrderItem`),
  CONSTRAINT `idProductItem`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrder`
    FOREIGN KEY (idOrder)
    REFERENCES Orders(idOrder)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Equipment` (
  `idProduct` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductEquipment`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Materials` (
  `idProduct` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductMaterials`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Flies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Flies` (
  `idProduct` INT NOT NULL,
  `size` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductFlies`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- =========================
-- CUSTOMERS
-- =========================
INSERT INTO Customers (idCustomer, name, address, phone) VALUES
(1, 'John Strange', '123 River Rd', '906-555-1111'),
(2, 'Sarah Miller', '456 Lake St', '906-555-2222'),
(3, 'Tyler Woods', '789 Pine Ave', '906-555-3333'),
(4, 'Emma Johnson', '321 Cedar Ln', '906-555-4444'),
(5, 'Chris Adams', '654 Birch St', '906-555-5555'),
(6, 'Liam Carter', '987 Oak Dr', '906-555-6666'),
(7, 'Olivia Brown', '222 Maple Rd', '906-555-7777'),
(8, 'Noah Davis', '111 Spruce Ln', '906-555-8888'),
(9, 'Ava Wilson', '555 Elm St', '906-555-9999'),
(10, 'Ethan Moore', '999 Pine Rd', '906-555-0000');

-- =========================
-- PRODUCTS
-- =========================
INSERT INTO Products (idProduct, title, price, description, color, category, imagePath) VALUES
-- Flies
(1, 'Wooly Bugger', 3.99, 'Streamer fly', 'Olive','flies', './assets/WoolyBugger.jpeg'),
(2, 'Adams Dry Fly', 2.49, 'Dry fly', 'Gray','flies', './assets/Adams.jpeg'),
(3, 'Pheasant Tail Nymph', 2.99, 'Nymph fly', 'Brown','flies', './assets/PheasantTail.jpeg'),
(4, 'Zebra Midge', 2.29, 'Small midge', 'Black','flies', './assets/ZebraMidge.jpeg'),
(5, 'Elk Hair Caddis', 2.79, 'Caddis imitation', 'Tan', 'flies', './assets/ElkHairCaddis.jpeg'),
(6, 'Stonefly Nymph', 3.49, 'Large nymph', 'Dark Brown', 'flies', './assets/StoneflyNymph.jpeg'),

-- Equipment
(7, 'Fly Rod 5WT', 149.99, 'Beginner rod', 'Black', 'equipment','./assets/FlyRod5wt.jpeg'),
(8, 'Fly Rod 8WT', 199.99, 'Heavy rod', 'Green','equipment', './assets/FlyRod8wt.jpeg'),
(9, 'Fly Reel Standard', 89.99, 'Smooth reel', 'Silver', 'equipment','./assets/FlyReelStandard.jpeg'),
(10, 'Fly Reel Pro', 129.99, 'High-end reel', 'Black', 'equipment','./assets/FlyReelPro.jpeg'),
(11, 'Floating Fly Line', 59.99, 'Floating line', 'Yellow','equipment', './assets/FlyLineFloating.jpeg'),
(12, 'Waders', 199.99, 'Chest waders', 'Brown', 'equipment','./assets/waders.jpeg'),

-- Materials
(13, 'Hackle Feather Pack', 12.99, 'Feathers', 'Mixed','materials', './assets/Hackle.jpeg'),
(14, 'Thread Spool', 4.99, 'Thread', 'Black','materials', './assets/flyThread.jpeg'),
(15, 'Hook Pack Size 10', 9.99, 'Hooks', 'Silver', 'materials','./assets/HookPack.jpeg'),
(16, 'Bead Heads', 6.99, 'Beads', 'Gold', 'materials','./assets/BeadHeads.jpeg'),
(17, 'Dubbing Pack', 8.99, 'Dubbing', 'Mixed', 'materials','./assets/Dubbing.jpeg');

-- =========================
-- FLIES
-- =========================
INSERT INTO Flies (idProduct, size, type) VALUES
(1, '8', 'Streamer'),
(2, '14', 'Dry'),
(3, '16', 'Nymph'),
(4, '18', 'Midge'),
(5, '12', 'Dry'),
(6, '10', 'Nymph');

-- =========================
-- EQUIPMENT
-- =========================
INSERT INTO Equipment (idProduct, type, size, gender) VALUES
(7, 'Rod', '5WT', 'Unisex'),
(8, 'Rod', '8WT', 'Unisex'),
(9, 'Reel', 'Medium', 'Unisex'),
(10, 'Reel', 'Large', 'Unisex'),
(11, 'Line', 'WF5F', 'Unisex'),
(12, 'Waders', 'L', 'Unisex');

-- =========================
-- MATERIALS
-- =========================
INSERT INTO Materials (idProduct, amount, type) VALUES
(13, '20 pack', 'Feather'),
(14, '1 spool', 'Thread'),
(15, '25 pack', 'Hook'),
(16, '50 pack', 'Bead'),
(17, '1 bag', 'Dubbing');

-- =========================
-- ORDERS
-- =========================
INSERT INTO Orders (idOrder, OrderDate, idCustomer) VALUES
(1, '2026-03-01', 1),
(2, '2026-03-02', 2),
(3, '2026-03-03', 3),
(4, '2026-03-04', 4),
(5, '2026-03-05', 5),
(6, '2026-03-06', 6),
(7, '2026-03-07', 7),
(8, '2026-03-08', 8),
(9, '2026-03-09', 9),
(10, '2026-03-10', 10);

-- =========================
-- ORDER ITEMS
-- =========================
INSERT INTO OrderItems (idOrderItem, idProduct, checkout_price, idOrder) VALUES
(1, 1, 3.99, 1),
(2, 7, 149.99, 1),

(3, 2, 2.49, 2),
(4, 13, 12.99, 2),

(5, 3, 2.99, 3),
(6, 9, 89.99, 3),

(7, 4, 2.29, 4),
(8, 14, 4.99, 4),

(9, 5, 2.79, 5),
(10, 10, 129.99, 5),

(11, 6, 3.49, 6),
(12, 11, 59.99, 6),

(13, 1, 3.99, 7),
(14, 12, 199.99, 7),

(15, 2, 2.49, 8),
(16, 15, 9.99, 8),

(17, 3, 2.99, 9),
(18, 16, 6.99, 9),

(19, 4, 2.29, 10),
(20, 17, 8.99, 10);