-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 17:08:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema final-project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final-project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final-project` DEFAULT CHARACTER SET utf8 ;
USE `final-project` ;

-- -----------------------------------------------------
-- Table `final-project`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Products` (
  `idProduct` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `price` DECIMAL(8,2) NULL,
  `description` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `imagePath` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `final-project`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Customers` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Orders` (
  `idOrder` INT NOT NULL,
  `OrderDate`  DATE NULL,
  `idCustomer` int NULL,
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `idCustomer`
    FOREIGN KEY (idCustomer)
    REFERENCES Customers(idCustomer)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`OrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`OrderItems` (
  `idOrderItem` INT NOT NULL,
  `idProduct`int NULL,
  `checkout_price` double NULL,
  `idOrder` int NULL,
  PRIMARY KEY (`idOrderItem`),
  CONSTRAINT `idProductItem`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrder`
    FOREIGN KEY (idOrder)
    REFERENCES Orders(idOrder)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Equipment` (
  `idProduct` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductEquipment`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Materials` (
  `idProduct` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductMaterials`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final-project`.`Flies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final-project`.`Flies` (
  `idProduct` INT NOT NULL,
  `size` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `idProductFlies`
    FOREIGN KEY (idProduct)
    REFERENCES Products(idProduct)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;